create table "PREFERENCES_METADATA" (
   "SLUG" VARCHAR NOT NULL PRIMARY KEY,
   "DESCRIPTION" VARCHAR NOT NULL,
   "SCHEMA" VARCHAR NOT NULL
);

create table "PREFERENCES" (
   "ID" VARCHAR NOT NULL,
   "PREFERENCES_METADATA_SLUG" VARCHAR NOT NULL,
   "PAYLOAD" VARCHAR NOT NULL,
   "CREATED" TIMESTAMP NOT NULL DEFAULT current_timestamp,
   "UPDATED" TIMESTAMP NOT NULL DEFAULT current_timestamp
);

alter table "PREFERENCES" add constraint "compound_pk" primary key (
   "ID","PREFERENCES_METADATA_SLUG"
);

alter table "PREFERENCES" add constraint "PREFERENCES_METADATA_SLUG_FK" foreign key (
   "PREFERENCES_METADATA_SLUG"
)
references "PREFERENCES_METADATA"("SLUG") on
update NO ACTION on
delete NO ACTION;